/* SPDX-FileCopyrightText: 2026 UPBGE Authors
 *
 * SPDX-License-Identifier: GPL-2.0-or-later */

/** \file LN_NodeRegistry.h
 *  \ingroup logicnodes
 */

#pragma once

#include <string>
#include <vector>

#include "LN_Types.h"

enum class LN_NodeKind : uint16_t {
  EventOnInit = 0,
  EventOnFixedUpdate,
  OnNextFrame,
  Once,
  Branch,
  Gate,
  GateList,
  ValueChanged,
  ValueChangedTo,
  Delay,
  Timer,
  Pulsify,
  Barrier,
  LimitRange,
  RandomValue,
  ValueSwitch,
  ValueSwitchList,
  ValueSwitchListCompare,
  Typecast,
  ValueValid,
  StoreValue,
  HasProperty,
  ToggleProperty,
  ModifyProperty,
  ModifyPropertyClamped,
  IsNone,
  NotNone,
  GetTreeProperty,
  SetTreeProperty,
  GetGlobalProperty,
  SetGlobalProperty,
  ListGlobalProperties,
  LoadVariable,
  SaveVariable,
  LoadVariableDict,
  SaveVariableDict,
  ClearVariables,
  ListSavedVariables,
  RemoveVariable,
  KeyboardKey,
  KeyboardActive,
  KeyCode,
  KeyLogger,
  MouseButton,
  MouseMoved,
  MouseWheel,
  CursorPosition,
  CursorMovement,
  SetCursorVisibility,
  SetCursorPosition,
  GamepadActive,
  GamepadButton,
  GamepadStick,
  GamepadVibration,
  GamepadLook,
  MouseLook,
  RemoveObject,
  AddObject,
  SpawnPool,
  SetParent,
  FindObject,
  ObjectByName,
  GetOwner,
  GetParent,
  GetChild,
  GetChildByName,
  RemoveParent,
  MouseOver,
  GetGravity,
  SetGravity,
  GetTimescale,
  SetTimescale,
  GetActiveCamera,
  SetCamera,
  SetCameraFov,
  SetCameraOrthoScale,
  WorldToScreen,
  ScreenToWorld,
  GetFullscreen,
  SetFullscreen,
  GetResolution,
  SetResolution,
  GetVSync,
  SetVSync,
  ShowFramerate,
  ShowProfile,
  GetCollisionGroup,
  SetCollisionGroup,
  SetPhysics,
  SetDynamics,
  RebuildCollisionShape,
  SetRigidBodyAttribute,
  GetCharacterInfo,
  CharacterJump,
  SetCharacterGravity,
  SetCharacterJumpSpeed,
  SetCharacterMaxJumps,
  SetCharacterWalkDirection,
  SetCharacterVelocity,
  VehicleControl,
  VehicleAccelerate,
  VehicleBrake,
  VehicleSteer,
  VehicleSetAttributes,
  ValueBool,
  ValueInt,
  ValueFloat,
  ValueString,
  StringOperation,
  FormattedString,
  ValueColor,
  ColorRGB,
  ColorRGBA,
  ValueVector,
  Euler,
  VectorToRotation,
  CombineXY,
  CombineXYZ,
  SeparateXY,
  SeparateXYZ,
  InvertValue,
  ClampValue,
  MapRange,
  Compare,
  Threshold,
  RangedThreshold,
  WithinRange,
  Math,
  VectorMath,
  GetGamePropertyInt,
  GetGamePropertyFloat,
  GetGamePropertyBool,
  GetGamePropertyString,
  GetLightColor,
  GetLightPower,
  ApplyImpulse,
  MakeLightUnique,
  SetLightColor,
  SetLightPower,
  SetLightShadow,
  ApplyMovement,
  ApplyRotation,
  ApplyForce,
  ApplyTorque,
  SetGamePropertyInt,
  SetGamePropertyFloat,
  SetGamePropertyBool,
  SetGamePropertyString,
  Raycast,
  RaycastAll,
  ShapeCast,
  ShapeCastAll,
  Time,
  DeltaFactor,
  StartLogicTree,
  StopLogicTree,
  RunLogicTree,
  LogicTreeStatus,
  InstallLogicTree,
  Print,
  QuitGame,
  RestartGame,
  PlayAction,
  StopAction,
  SetActionFrame,
  ActionDone,
  ObjectsColliding,
  StopAllSounds,
  PlaySound,
  PlaySound3D,
  PauseSound,
  ResumeSound,
  StopSound,
  GetBoneHeadWorld,
  LoadBlendFile,
  SendEvent,
  ReceiveEvent,
  Collision,
  OnCollision,
  AnimationStatus,
  MoveToward,
  Navigate,
  FollowPath,
  Translate,
  SlowFollow,
  LoadScene,
  SetScene,
  GetScene,
  GetCollection,
  GetCollectionObjects,
  GetCollectionObjectNames,
  SetCollectionVisibility,
  SetOverlayCollection,
  RemoveOverlayCollection,
  SaveGame,
  LoadGame,
  AlignAxisToVector,
  RotateToward,
  ReplaceMesh,
  CopyProperty,
  GetObjectAttribute,
  SetObjectAttribute,
  Loop,
  LoopFromList,
  ListLength,
  ListGetItem,
  ListRandomItem,
  MakeList,
  ListExtend,
  DictGetKey,
  MakeDict,
  DictLength,
  DictGetKeys,
  GetBoneTailWorld,
  GetBoneLength,
  GetBoneCenterWorld,
  EmptyList,
  EmptyDict,
  DictHasKey,
  ListDuplicate,
  DictMerge,
  ListContains,
  ListAppend,
  ListRemoveIndex,
  ListRemoveValue,
  ListSetIndex,
  DictSetKey,
  DictRemoveKey,
  ListFromItems,
  GetBoneHeadPoseWorld,
  GetBoneTailPoseWorld,
  GetBoneCenterPoseWorld,
  SetBonePoseLocation,
  SetBonePoseRotation,
  SetBoneConstraintInfluence,
  SetMaterialSlot,
  MouseRay,
  CameraRay,
  EvaluateCurve,
  EvaluateProperty,
  ToggleTreeProperty,
  RandomFloat,
  RandomInt,
  RandomVector,
  TweenValue,
  Formula,
  AddPhysicsConstraint,
  GetRigidBodyConstraints,
  RemovePhysicsConstraint,
  ProjectileRay,
  GetBoneAttribute,
  SetBoneAttribute,
  ReservedRemovedNode,
  SetBoneConstraintTarget,
  SetBoneConstraintAttribute,
  GetMaterialFromSlot,
  GetMaterialSlotCount,
  GetMaterialName,
  GetMaterialParameter,
  SetMaterialParameter,
  SetGeometryNodesInput,
  GetEditorNodeValue,
  SetEditorNodeValue,
  MakeNodeTreeUnique,
  SetNodeMute,
  EnableDisableModifier,
  AssignGeometryNodesModifier,
  GetNodeGroupSocketValue,
  SetNodeGroupSocketValue,
  PlayMaterialSequence,
  CombineXYZW,
  ResizeVector,
  XYZToMatrix,
  MatrixToXYZ,
  VectorRotate,
  FilePath,
  StartSpeaker,
  GetSound,
  GetImage,
  GetFont,
  GetObjectID,
  GetAxisVector,
  DrawLine,
  DrawCube,
  DrawBox,
  Draw,
  JoinPath,
  GetMasterFolder,
  LoadFileContent,
  SetCustomCursor,
  GetBonePoseRotation,
  GetBonePoseScale,
  GetBonePoseTransform,
  SetBonePoseScale,
  SetBonePoseTransform,
  GetDistance,
  GetGroupCenterPosition,
  ApplyForceToTarget,
  SeparateEuler,
  GetRigidBodyAttribute,
  BooleanEdge,
  Cooldown,
};

enum class LN_RequiredPhase : uint8_t {
  None = 0,
  OnInit,
  FixedUpdate,
};

enum class LN_ExecutionClass : uint8_t {
  SnapshotReadOnly = 0,
  CommandEmitting,
  MainThreadOnly,
};

enum class LN_PinKind : uint8_t {
  Value = 0,
  Condition,
  Execution,
};

struct LN_PinDefinition {
  std::string name;
  std::string socket_idname;
  LN_PinKind kind = LN_PinKind::Value;
  LN_ValueType value_type = LN_ValueType::None;
  bool requires_link = false;
};

struct LN_NodeDefinition {
  std::string idname;
  LN_NodeKind kind = LN_NodeKind::ValueBool;
  std::vector<LN_PinDefinition> inputs;
  std::vector<LN_PinDefinition> outputs;
  std::string category;
  std::string ui_name;
  std::string ui_description;
  bool has_side_effects = false;
  LN_RequiredPhase required_phase = LN_RequiredPhase::None;
  bool requires_jolt = false;
  bool future_pure_batchable = false;
  LN_ExecutionClass execution_class = LN_ExecutionClass::SnapshotReadOnly;
};

class LN_NodeRegistry {
 public:
  LN_NodeRegistry();

  static const LN_NodeRegistry &GetBuiltin();

  const LN_NodeDefinition *FindNodeDefinition(const std::string &idname) const;
  const std::vector<LN_NodeDefinition> &GetNodeDefinitions() const
  {
    return m_definitions;
  }

 private:
  std::vector<LN_NodeDefinition> m_definitions;
};
