# SPDX-FileCopyrightText: 2026 UPBGE Authors
#
# SPDX-License-Identifier: GPL-2.0-or-later

"""Regenerate logic_node_addon_reference_generated.py from bge_netlogic menu labels.

Run from repo root (stdout must NOT be redirected into the output file):

  ./build_linux/bin/blender --background --python \\
    scripts/startup/bl_ui/generate_logic_node_addon_reference.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

import bpy

REPO_ROOT = Path(__file__).resolve().parents[3]
MENU = REPO_ROOT / "scripts/addons_core/bge_netlogic/ui/node_menu.py"
OUT = Path(__file__).with_name("logic_node_addon_reference_generated.py")


def main() -> int:
    text = MENU.read_text(encoding="utf-8")
    label_to_addon: dict[str, str] = {}
    for match in re.finditer(
        r'insertNode\(\s*layout\s*,\s*["\']([^"\']+)["\']\s*,\s*["\']([^"\']+)["\']',
        text,
    ):
        bl_idname, label = match.group(1), match.group(2)
        key = label.strip().lower()
        if key:
            label_to_addon[key] = bl_idname  # last menu entry wins for duplicate labels

    lines = [
        "# SPDX-FileCopyrightText: 2026 UPBGE Authors",
        "# SPDX-License-Identifier: GPL-2.0-or-later",
        "# Auto-generated by generate_logic_node_addon_reference.py — do not edit by hand.",
        "NATIVE_ONLY = frozenset({",
        '    "LogicNativeActionDone",',
        '    "LogicNativeBooleanEdge",',
        '    "LogicNativeCooldown",',
        '    "LogicNativeDictHasKey",',
        '    "LogicNativeDictLength",',
        '    "LogicNativeDictMerge",',
        '    "LogicNativeGetBoneLength",',
        '    "LogicNativeListContains",',
        '    "LogicNativeListLength",',
        '    "LogicNativeObjectsColliding",',
        '    "LogicNativeOnce",',
        '    "LogicNativeValueColor",',
        '    "LogicNativeVehicleControl",',
        "})",
        "",
        "LABEL_TO_ADDON = {",
    ]
    for label in sorted(label_to_addon):
        lines.append(f"    {label!r}: {label_to_addon[label]!r},")
    lines.append("}")
    lines.append("")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {len(label_to_addon)} entries to {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
