# SPDX-FileCopyrightText: 2026 UPBGE Authors
# SPDX-License-Identifier: GPL-2.0-or-later
# Auto-generated by generate_logic_node_parity_overrides.py

PARITY_SOCKET_OVERRIDES: dict[str, tuple[dict[str, str], dict[str, str]]] = {
    "LogicNativeCombineXYZW": (
        {'X': 'socket', 'Y': 'socket', 'Z': 'socket', 'W': 'socket'},
        {'Vector': 'socket'},
    ),
    "LogicNativeDrawBox": (
        {'Condition': 'socket', 'Color': 'socket', 'Origin': 'socket', 'Width': 'socket', 'Length': 'socket', 'Height': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativeFilePath": (
        {'Value': 'socket'},
        {'Path': 'socket'},
    ),
    "LogicNativeGetAxisVector": (
        {'Object': 'socket'},
        {'Vector': 'socket'},
    ),
    "LogicNativeGetObjectID": (
        {'Object': 'socket'},
        {'ID': 'socket'},
    ),
    "LogicNativeMatrixToXYZ": (
        {'Matrix': 'socket'},
        {'Vector': 'socket'},
    ),
    "LogicNativeSetBoneConstraintAttribute": (
        {'Condition': 'socket', 'Armature': 'socket', 'Bone': 'socket', 'Constraint': 'socket', 'Attribute': 'socket', 'Value': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativeAddObject": (
        {'Condition': 'socket', 'Object to Add': 'socket', 'Copy Transform': 'socket', 'Life': 'socket', 'Full Copy': 'socket'},
        {'Out': 'socket'},
    ),
    "LogicNativeAlignAxisToVector": (
        {'Condition': 'socket', 'Object': 'socket', 'Vector': 'socket', 'Axis': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativeApplyForce": (
        {'Condition': 'socket', 'Object': 'socket', 'Vector': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativeApplyImpulse": (
        {'Condition': 'socket', 'Object': 'socket', 'Impulse': 'socket', 'Vector': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativeApplyMovement": (
        {'Condition': 'socket', 'Object': 'socket', 'Vector': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativeApplyRotation": (
        {'Condition': 'socket', 'Object': 'socket', 'Rotation': 'socket', 'Local': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativeApplyTorque": (
        {'Condition': 'socket', 'Object': 'socket', 'Vector': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativeCollision": (
        {'Object': 'socket', 'Property': 'socket', 'Material': 'socket'},
        {'Colliding': 'socket',
         'Collided Object': 'socket',
         'Collided Objects': 'socket',
         'Contact Count': 'socket',
         'Point': 'socket',
         'Points': 'socket',
         'Normal': 'socket',
         'Normals': 'socket'},
    ),
    "LogicNativeOnCollision": (
        {'Object': 'socket', 'Property': 'socket', 'Material': 'socket'},
        {'On Enter': 'socket',
         'On Stay': 'socket',
         'On Exit': 'socket',
         'Colliding': 'socket',
         'Collided Object': 'socket',
         'Collided Objects': 'socket',
         'Contact Count': 'socket',
         'Point': 'socket',
         'Points': 'socket',
         'Normal': 'socket',
         'Normals': 'socket'},
    ),
    "LogicNativeColorRGB": (
        {},
        {'Color': 'socket'},
    ),
    "LogicNativeColorRGBA": (
        {},
        {'Color': 'socket'},
    ),
    "LogicNativeCombineXY": (
        {'X': 'socket', 'Y': 'socket'},
        {'Vector': 'socket'},
    ),
    "LogicNativeCombineXYZ": (
        {'X': 'socket', 'Y': 'socket', 'Z': 'socket'},
        {'Vector': 'socket'},
    ),
    "LogicNativeCompare": (
        {'A': 'socket', 'B': 'socket'},
        {'Result': 'socket'},
    ),
    "LogicNativeCopyProperty": (
        {'Condition': 'socket', 'Source': 'socket', 'Target': 'socket', 'Property': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativeCursorMovement": (
        {},
        {'Movement': 'socket', 'X': 'socket', 'Y': 'socket'},
    ),
    "LogicNativeCursorPosition": (
        {},
        {'Position': 'socket', 'X': 'socket', 'Y': 'socket'},
    ),
    "LogicNativeDelay": (
        {'Condition': 'socket', 'Delay': 'socket'},
        {'Out': 'socket'},
    ),
    "LogicNativeDeltaFactor": (
        {},
        {'Factor': 'socket'},
    ),
    "LogicNativeDictGetKey": (
        {'Dictionary': 'socket', 'Key': 'socket'},
        {'Value': 'socket'},
    ),
    "LogicNativeDictGetKeys": (
        {'Dictionary': 'socket'},
        {'Keys': 'socket'},
    ),
    "LogicNativeEmptyDict": (
        {},
        {'Dictionary': 'socket'},
    ),
    "LogicNativeEmptyList": (
        {'Length': 'socket'},
        {'List': 'socket'},
    ),
    "LogicNativeEuler": (
        {'X': 'socket', 'Y': 'socket', 'Z': 'socket'},
        {'Rotation': 'socket'},
    ),
    "LogicNativeVectorToRotation": (
        {'Direction': 'socket', 'Up': 'socket'},
        {'Rotation': 'socket'},
    ),
    "LogicNativeEvaluateCurve": (
        {'Curve': 'socket', 'Factor': 'socket'},
        {'Vector': 'socket'},
    ),
    "LogicNativeFormattedString": (
        {'Format': 'socket'},
        {'String': 'socket'},
    ),
    "LogicNativeGamepadButton": (
        {'Index': 'socket'},
        {'Pressed': 'socket', 'Strength': 'socket'},
    ),
    "LogicNativeGamepadLook": (
        {'Condition': 'socket', 'Body': 'socket', 'Head': 'socket', 'Inverted': 'socket', 'Index': 'socket', 'Sensitivity': 'socket', 'Exponent': 'socket', 'Cap Left / Right': 'socket', 'Cap Up / Down': 'socket', 'Threshold': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativeGamepadVibration": (
        {'Condition': 'socket', 'Index': 'socket', 'Left': 'socket', 'Right': 'socket', 'Time': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativeGamepadStick": (
        {'Invert X': 'socket', 'Invert Y': 'socket', 'Index': 'socket', 'Sensitivity': 'socket', 'Threshold': 'socket'},
        {'X': 'socket', 'Y': 'socket', 'Vector': 'socket'},
    ),
    "LogicNativeGetBoneCenterWorld": (
        {'Object': 'socket', 'Bone Name': 'socket'},
        {'Position': 'socket'},
    ),
    "LogicNativeGetBoneHeadPoseWorld": (
        {'Object': 'socket', 'Bone Name': 'socket'},
        {'Position': 'socket'},
    ),
    "LogicNativeGetBoneCenterPoseWorld": (
        {'Object': 'socket', 'Bone Name': 'socket'},
        {'Position': 'socket'},
    ),
    "LogicNativeGetBonePoseRotation": (
        {'Object': 'socket', 'Bone Name': 'socket'},
        {'Rotation': 'socket'},
    ),
    "LogicNativeGetBonePoseScale": (
        {'Object': 'socket', 'Bone Name': 'socket'},
        {'Scale': 'socket'},
    ),
    "LogicNativeGetBonePoseTransform": (
        {'Object': 'socket', 'Bone Name': 'socket'},
        {'Location': 'socket', 'Rotation': 'socket', 'Scale': 'socket'},
    ),
    "LogicNativeGetBoneHeadWorld": (
        {'Object': 'socket', 'Bone Name': 'socket'},
        {'Position': 'socket'},
    ),
    "LogicNativeGetBoneTailPoseWorld": (
        {'Object': 'socket', 'Bone Name': 'socket'},
        {'Position': 'socket'},
    ),
    "LogicNativeGetBoneTailWorld": (
        {'Object': 'socket', 'Bone Name': 'socket'},
        {'Position': 'socket'},
    ),
    "LogicNativeGetChild": (
        {'Parent': 'socket', 'Index': 'socket'},
        {'Child': 'socket'},
    ),
    "LogicNativeGetCollisionGroup": (
        {},
        {'Bitmask': 'socket'},
    ),
    "LogicNativeGetLightColor": (
        {'Light Object': 'socket'},
        {'Color': 'socket'},
    ),
    "LogicNativeGetLightPower": (
        {'Light Object': 'socket'},
        {'Power': 'socket'},
    ),
    "LogicNativeGetObjectAttribute": (
        {'Object': 'socket'},
        {
            'Name': 'socket',
            'Vector': 'socket',
            'Visible': 'socket',
            'Position': 'socket',
            'Orientation': 'socket',
            'Scale': 'socket',
            'Color': 'socket',
        },
    ),
    "LogicNativeGetTreeProperty": (
        {'Property': 'socket'},
        {'Property': 'socket'},
    ),
    "LogicNativeInstallLogicTree": (
        {'Condition': 'socket', 'Object': 'socket', 'Tree': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativeInvert": (
        {'Value': 'socket'},
        {'Result': 'socket'},
    ),
    "LogicNativeKeyboardKey": (
        {'Key': 'socket'},
        {'If Pressed': 'socket'},
    ),
    "LogicNativeLimitRange": (
        {'Value': 'socket', 'Min': 'socket', 'Max': 'socket'},
        {'Result': 'socket'},
    ),
    "LogicNativeListExtend": (
        {'List A': 'socket', 'List B': 'socket'},
        {'List': 'socket'},
    ),
    "LogicNativeListGetItem": (
        {'List': 'socket', 'Index': 'socket'},
        {'Value': 'socket'},
    ),
    "LogicNativeLoadScene": (
        {'Condition': 'socket', 'Scene': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativeLogicTreeStatus": (
        {'Object': 'socket', 'Tree Name': 'socket'},
        {'Running': 'socket', 'Stopped': 'socket'},
    ),
    "LogicNativeLoop": (
        {'Condition': 'socket', 'Count': 'socket'},
        {'Loop': 'socket', 'Index': 'socket', 'Value': 'socket'},
    ),
    "LogicNativeLoopFromList": (
        {'Condition': 'socket', 'List': 'socket'},
        {'Loop': 'socket', 'Index': 'socket', 'Value': 'socket'},
    ),
    "LogicNativeMakeDict": (
        {'Key': 'socket', 'Value': 'socket'},
        {'Dictionary': 'socket'},
    ),
    "LogicNativeMakeLightUnique": (
        {'Condition': 'socket', 'Light Object': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativeMakeList": (
        {'Item A': 'socket', 'Item B': 'socket', 'Item C': 'socket'},
        {'List': 'socket'},
    ),
    "LogicNativeMapRange": (
        {'Value': 'socket', 'From Min': 'socket', 'From Max': 'socket', 'To Min': 'socket', 'To Max': 'socket'},
        {'Result': 'socket'},
    ),
    "LogicNativeMath": (
        {'A': 'socket', 'B': 'socket'},
        {'Result': 'socket'},
    ),
    "LogicNativeModifyProperty": (
        {'Condition': 'socket', 'Object': 'socket', 'Property': 'socket', 'Value': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativeModifyPropertyClamped": (
        {
            'Condition': 'socket',
            'Object': 'socket',
            'Property': 'socket',
            'Value': 'socket',
            'Min': 'socket',
            'Max': 'socket',
        },
        {'Done': 'socket'},
    ),
    "LogicNativeMouseButton": (
        {'Button': 'socket'},
        {'If Pressed': 'socket'},
    ),
    "LogicNativeMouseWheel": (
        {},
        {'When Scrolled': 'socket', 'Difference': 'socket'},
    ),
    "LogicNativeMoveToward": (
        {'Condition': 'socket', 'Object': 'socket', 'Target': 'socket', 'Speed': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativePauseSound": (
        {'Condition': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativePlayAction": (
        {'Condition': 'socket', 'Object': 'socket', 'Animation Layer': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativePlaySound": (
        {'Condition': 'socket', 'Volume': 'socket', 'Pitch': 'socket', 'Loop': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativePlaySound3D": (
        {'Condition': 'socket', 'Speaker': 'socket', 'Volume': 'socket', 'Pitch': 'socket', 'Loop': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativePrint": (
        {'Condition': 'socket', 'Value': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativePulsify": (
        {'Condition': 'socket', 'Gap': 'socket'},
        {'Out': 'socket'},
    ),
    "LogicNativeRandomValue": (
        {'Min': 'socket', 'Max': 'socket'},
        {'Value': 'socket'},
    ),
    "LogicNativeRangedThreshold": (
        {'Value': 'socket', 'Min': 'socket', 'Max': 'socket'},
        {'Result': 'socket'},
    ),
    "LogicNativeRaycast": (
        {
            'Flow': 'socket',
            'Caster': 'socket',
            'Ignore Object': 'socket',
            'Origin': 'socket',
            'Destination': 'socket',
            'Local': 'socket',
            'Property': 'socket',
            'X-Ray': 'socket',
            'Mask': 'socket',
            'Visualize': 'socket',
        },
        {
            'Done': 'socket',
            'Has Result': 'socket',
            'Hit Object': 'socket',
            'Point': 'socket',
            'Normal': 'socket',
            'Direction': 'socket',
            'Distance': 'socket',
            'Face Index': 'socket',
            'Has UV': 'socket',
            'UV': 'socket',
        },
    ),
    "LogicNativeRaycastAll": (
        {
            'Flow': 'socket',
            'Caster': 'socket',
            'Ignore Object': 'socket',
            'Origin': 'socket',
            'Destination': 'socket',
            'Local': 'socket',
            'Property': 'socket',
            'X-Ray': 'socket',
            'Mask': 'socket',
            'Visualize': 'socket',
        },
        {
            'Done': 'socket',
            'Has Result': 'socket',
            'Hit Count': 'socket',
            'Hit Objects': 'socket',
            'Points': 'socket',
            'Normals': 'socket',
            'Distances': 'socket',
            'Face Indices': 'socket',
            'Has UVs': 'socket',
            'UVs': 'socket',
        },
    ),
    "LogicNativeReceiveEvent": (
        {'Subject': 'socket', 'Target': 'socket'},
        {'Out': 'socket', 'Received': 'socket', 'Content': 'socket', 'Messenger': 'socket'},
    ),
    "LogicNativeRemoveObject": (
        {'Condition': 'socket', 'Object': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativeRemoveParent": (
        {'Condition': 'socket', 'Child Object': 'socket'},
        {'Out': 'socket'},
    ),
    "LogicNativeReplaceMesh": (
        {'Condition': 'socket', 'Object': 'socket', 'Mesh Object': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativeResumeSound": (
        {'Condition': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativeRotateToward": (
        {'Condition': 'socket', 'Object': 'socket', 'Target': 'socket', 'Factor': 'socket', 'Rot Axis': 'socket', 'Front': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativeRunLogicTree": (
        {'Condition': 'socket', 'Object': 'socket', 'Tree Name': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativeSendEvent": (
        {'Condition': 'socket', 'Subject': 'socket', 'Content': 'socket', 'Messenger': 'socket', 'Target': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativeSeparateXY": (
        {'Vector': 'socket'},
        {'X': 'socket', 'Y': 'socket'},
    ),
    "LogicNativeSeparateEuler": (
        {'Rotation': 'socket'},
        {'X': 'socket', 'Y': 'socket', 'Z': 'socket'},
    ),
    "LogicNativeSeparateXYZ": (
        {'Vector': 'socket'},
        {'X': 'socket', 'Y': 'socket', 'Z': 'socket'},
    ),
    "LogicNativeSetActionFrame": (
        {'Condition': 'socket', 'Object': 'socket', 'Animation Layer': 'socket', 'Frame': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativeSetBoneConstraintInfluence": (
        {'Condition': 'socket', 'Object': 'socket', 'Bone Name': 'socket', 'Constraint Name': 'socket', 'Influence': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativeSetBonePoseLocation": (
        {'Condition': 'socket', 'Object': 'socket', 'Bone Name': 'socket', 'Location': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativeSetBonePoseRotation": (
        {'Condition': 'socket', 'Object': 'socket', 'Bone Name': 'socket', 'Rotation': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativeSetBonePoseScale": (
        {'Condition': 'socket', 'Object': 'socket', 'Bone Name': 'socket', 'Scale': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativeSetBonePoseTransform": (
        {'Condition': 'socket', 'Object': 'socket', 'Bone Name': 'socket', 'Location': 'socket', 'Rotation': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativeSetCollisionGroup": (
        {'Condition': 'socket', 'Bitmask': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativeSetCursorPosition": (
        {'Condition': 'socket', 'Screen X': 'socket', 'Screen Y': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativeSetCursorVisibility": (
        {'Condition': 'socket', 'Visible': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativeSetDynamics": (
        {'Condition': 'socket', 'Object': 'socket', 'Enabled': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativeRebuildCollisionShape": (
        {'Condition': 'socket', 'Object': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativeSetGravity": (
        {'Condition': 'socket', 'Gravity': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativeSetLightColor": (
        {'Condition': 'socket', 'Light Object': 'socket', 'Value': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativeSetLightPower": (
        {'Condition': 'socket', 'Light Object': 'socket', 'Power': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativeSetLightShadow": (
        {'Condition': 'socket', 'Object': 'socket', 'Use Shadow': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativeSetMaterialSlot": (
        {'Condition': 'socket', 'Object': 'socket', 'Material': 'socket', 'Slot': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativeSetMaterialParameter": (
        {'Condition': 'socket', 'Object': 'socket', 'Slot': 'socket', 'Material': 'socket', 'Node Name': 'socket', 'Socket': 'socket', 'Value': 'socket', 'Float Value': 'socket', 'Integer Value': 'socket', 'Boolean Value': 'socket', 'Vector Value': 'socket', 'Color Value': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativeSetObjectAttribute": (
        {
            'Condition': 'socket',
            'XYZ': 'socket',
            'Object': 'socket',
            'Value': 'socket',
            'Position': 'socket',
            'Rotation': 'socket',
            'Scale': 'socket',
            'Color': 'socket',
            'Visible': 'socket',
            'Include Children': 'socket',
        },
        {'Done': 'socket'},
    ),
    "LogicNativeSetPhysics": (
        {'Condition': 'socket', 'Object': 'socket', 'Active': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativeGetRigidBodyAttribute": (
        {'Object': 'socket'},
        {
            'Valid': 'socket',
            'Value': 'socket',
            'Linear Damping': 'socket',
            'Angular Damping': 'socket',
            'Enabled': 'socket',
            'Allow Sleeping': 'socket',
            'Lock Translation': 'socket',
            'Lock Rotation': 'socket',
        },
    ),
    "LogicNativeSetRigidBodyAttribute": (
        {
            'Condition': 'socket',
            'Object': 'socket',
            'Value': 'socket',
            'Linear Damping': 'socket',
            'Angular Damping': 'socket',
            'Min Linear': 'socket',
            'Max Linear': 'socket',
            'Min Angular': 'socket',
            'Max Angular': 'socket',
            'Enabled': 'socket',
            'Allow Sleeping': 'socket',
            'Wake': 'socket',
            'Lock Translation': 'socket',
            'Lock Rotation': 'socket',
        },
        {'Done': 'socket'},
    ),
    "LogicNativeSetScene": (
        {'Condition': 'socket', 'Scene': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativeSetTimescale": (
        {'Condition': 'socket', 'Timescale': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativeSetTreeProperty": (
        {'Condition': 'socket', 'Name': 'socket', 'Value': 'socket'},
        {},
    ),
    "LogicNativeSlowFollow": (
        {'Condition': 'socket', 'Object': 'socket', 'Target': 'socket', 'Factor': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativeStopSound": (
        {'Condition': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativeStoreValue": (
        {'Condition': 'socket', 'Value': 'socket'},
        {'Done': 'socket', 'Stored Value': 'socket'},
    ),
    "LogicNativeStringOperation": (
        {'String': 'socket'},
        {'String': 'socket'},
    ),
    "LogicNativeTime": (
        {},
        {'Time': 'socket'},
    ),
    "LogicNativeValueBool": (
        {},
        {'Bool': 'socket'},
    ),
    "LogicNativeValueChanged": (
        {'Value': 'socket'},
        {'If Changed': 'socket', 'Old': 'socket', 'New': 'socket'},
    ),
    "LogicNativeValueChangedTo": (
        {'Value': 'socket', 'Target': 'socket'},
        {'Result': 'socket'},
    ),
    "LogicNativeValueFloat": (
        {},
        {'Float': 'socket'},
    ),
    "LogicNativeValueInt": (
        {},
        {'Int': 'socket'},
    ),
    "LogicNativeValueString": (
        {},
        {'String': 'socket'},
    ),
    "LogicNativeValueSwitch": (
        {'A if True, else B': 'socket', 'True': 'socket', 'False': 'socket'},
        {'Result': 'socket'},
    ),
    "LogicNativeValueVector": (
        {},
        {'Vector': 'socket'},
    ),
    "LogicNativeVectorMath": (
        {'Vector': 'socket'},
        {'Result': 'socket'},
    ),
    "LogicNativeVehicleSetAttributes": (
        {'Condition': 'socket', 'Collider': 'socket', 'Wheels': 'socket', 'Suspension': 'socket', 'Suspension Value': 'socket', 'Stiffness': 'socket', 'Stiffness Value': 'socket', 'Damping': 'socket', 'Damping Value': 'socket', 'Friction': 'socket', 'Friction Value': 'socket'},
        {'Done': 'socket'},
    ),
    "LogicNativeWithinRange": (
        {'Value': 'socket', 'Min': 'socket', 'Max': 'socket'},
        {'Result': 'socket'},
    ),
}
