# SPDX-FileCopyrightText: 2026 UPBGE Authors
#
# SPDX-License-Identifier: GPL-2.0-or-later

"""Native → addon reference for parity tooling."""

from pathlib import Path

_gen_path = Path(__file__).with_name("logic_node_addon_reference_generated.py")
_gen_ns: dict = {}
exec(_gen_path.read_text(encoding="utf-8"), _gen_ns)
LABEL_TO_ADDON = _gen_ns["LABEL_TO_ADDON"]
NATIVE_ONLY = _gen_ns["NATIVE_ONLY"]

_ov_path = Path(__file__).with_name("logic_node_parity_socket_overrides.py")
_ov_ns: dict = {}
exec(_ov_path.read_text(encoding="utf-8"), _ov_ns)
_PARITY_SOCKET_OVERRIDES = _ov_ns["PARITY_SOCKET_OVERRIDES"]

# Catalog labels differ from addon menu text (typed variants, wording).
NATIVE_TO_ADDON: dict[str, str] = {
    "LogicNativeValueChanged": "NLConditionValueChanged",
    "LogicNativeValueChangedTo": "NLConditionValueTriggerNode",
    "LogicNativeValueSwitchList": "NLValueSwitchList",
    "LogicNativeValueSwitchListCompare": "NLValueSwitchListCompare",
    "LogicNativeTypecast": "NLParameterTypeCast",
    "LogicNativeValueValid": "NLConditionValueValidNode",
    "LogicNativeHasProperty": "NLGameObjectHasPropertyParameterNode",
    "LogicNativeGetGamePropertyFloat": "NLGameObjectPropertyParameterNode",
    "LogicNativeGetGamePropertyInt": "NLGameObjectPropertyParameterNode",
    "LogicNativeGetGamePropertyBool": "NLGameObjectPropertyParameterNode",
    "LogicNativeGetGamePropertyString": "NLGameObjectPropertyParameterNode",
    "LogicNativeSetGamePropertyFloat": "NLSetGameObjectGamePropertyActionNode",
    "LogicNativeSetGamePropertyInt": "NLSetGameObjectGamePropertyActionNode",
    "LogicNativeSetGamePropertyBool": "NLSetGameObjectGamePropertyActionNode",
    "LogicNativeSetGamePropertyString": "NLSetGameObjectGamePropertyActionNode",
    "LogicNativeToggleProperty": "NLToggleGameObjectGamePropertyActionNode",
    "LogicNativeSetCursorVisibility": "NLActionSetMouseCursorVisibility",
    "LogicNativeStopAction": "NLActionStopAnimation",
    "LogicNativeSetActionFrame": "NLActionSetAnimationFrame",
    "LogicNativeGetBoneHeadWorld": "LogicNodeGetRigBoneAttribute",
    "LogicNativeGetBoneTailWorld": "LogicNodeGetRigBoneAttribute",
    "LogicNativeGetBoneCenterWorld": "LogicNodeGetRigBoneAttribute",
    "LogicNativeGetBoneHeadPoseWorld": "LogicNodeGetRigBoneAttribute",
    "LogicNativeGetBoneTailPoseWorld": "LogicNodeGetRigBoneAttribute",
    "LogicNativeGetBoneCenterPoseWorld": "LogicNodeGetRigBoneAttribute",
    "LogicNativeGetBonePoseRotation": "LogicNodeGetRigBoneAttribute",
    "LogicNativeGetBonePoseScale": "LogicNodeGetRigBoneAttribute",
    "LogicNativeGetBonePoseTransform": "LogicNodeGetRigBoneAttribute",
    "LogicNativeGetBoneAttribute": "LogicNodeGetRigBoneAttribute",
    "LogicNativeSetBonePoseRotation": "LogicNodeSetRigBoneAttribute",
    "LogicNativeSetBonePoseLocation": "LogicNodeSetRigBoneAttribute",
    "LogicNativeSetBonePoseScale": "LogicNodeSetRigBoneAttribute",
    "LogicNativeSetBonePoseTransform": "LogicNodeSetRigBoneAttribute",
    "LogicNativeSetBoneAttribute": "LogicNodeSetRigBoneAttribute",
    "LogicNativeSetBoneConstraintInfluence": "LogicNodeSetConstraintAttribute",
    "LogicNativeSetBoneConstraintTarget": "NLSetBoneConstraintTarget",
    "LogicNativeSetBoneConstraintAttribute": "LogicNodeSetConstraintAttribute",
    "LogicNativeCopyProperty": "NLCopyPropertyFromObject",
    "LogicNativeGamepadVibration": "NLGamepadVibration",
    "LogicNativeApplyMovement": "LogicNodeApplyTransform",
    "LogicNativeApplyRotation": "LogicNodeApplyTransform",
    "LogicNativeApplyForce": "LogicNodeApplyTransform",
    "LogicNativeApplyTorque": "LogicNodeApplyTransform",
    "LogicNativeApplyImpulse": "LogicNodeApplyTransform",
    "LogicNativeModifyProperty": "NLAddToGameObjectGamePropertyActionNode",
    "LogicNativeModifyPropertyClamped": "NLClampedModifyProperty",
    "LogicNativeFindObject": "NLActionFindObjectNode",
    "LogicNativeObjectByName": "LogicNodeObjectByName",
    "LogicNativeGetOwner": "NLOwnerGameObjectParameterNode",
    "LogicNativeGetChild": "NLParameterFindChildByIndexNode",
    "LogicNativeGetChildByName": "NLParameterFindChildByNameNode",
    "LogicNativePlayAction": "NLActionPlayActionNode",
    "LogicNativePlaySound": "NLActionStartSound",
    "LogicNativePlaySound3D": "NLActionStart3DSoundAdv",
    "LogicNativeSetMaterialSlot": "NLSetMaterial",
    "LogicNativeInstallLogicTree": "NLActionInstallSubNetwork",
    "LogicNativeGetObjectAttribute": "NLObjectAttributeParameterNode",
    "LogicNativeEvaluateProperty": "NLObjectPropertyOperator",
    "LogicNativeSetObjectAttribute": "NLSetObjectAttributeActionNode",
    "LogicNativeListGetItem": "NLGetListIndexNode",
    "LogicNativeListRandomItem": "NLGetRandomListIndex",
    "LogicNativeMakeList": "NLInitNewList",
    "LogicNativeListExtend": "NLExtendList",
    "LogicNativeMakeDict": "NLInitNewDict",
    "LogicNativeListDuplicate": "NLDuplicateList",
    "LogicNativeListAppend": "NLAppendListItem",
    "LogicNativeListRemoveIndex": "NLRemoveListIndex",
    "LogicNativeListRemoveValue": "NLRemoveListValue",
    "LogicNativeListSetIndex": "NLSetListIndex",
    "LogicNativeDictSetKey": "NLSetDictKeyValue",
    "LogicNativeDictRemoveKey": "NLSetDictDelKey",
    "LogicNativeListFromItems": "LogicNodeListFromItems",
    "LogicNativeGetTreeProperty": "LogicNodeGetLogicTreeProperty",
    "LogicNativeSetTreeProperty": "LogicNodeSetLogicTreeProperty",
    "LogicNativeToggleTreeProperty": "LogicNodeToggleLogicTreeProperty",
    "LogicNativeGetGlobalProperty": "NLParameterGetGlobalValue",
    "LogicNativeSetGlobalProperty": "NLActionSetGlobalValue",
    "LogicNativeListGlobalProperties": "NLActionListGlobalValues",
    "LogicNativeLoadVariable": "NLActionLoadVariable",
    "LogicNativeSaveVariable": "NLActionSaveVariable",
    "LogicNativeLoadVariableDict": "NLActionLoadVariables",
    "LogicNativeSaveVariableDict": "NLActionSaveVariables",
    "LogicNativeClearVariables": "NLActionClearVariables",
    "LogicNativeListSavedVariables": "NLActionListVariables",
    "LogicNativeRemoveVariable": "NLActionRemoveVariable",
    "LogicNativeRunLogicTree": "NLActionExecuteNetwork",
    "LogicNativeLogicTreeStatus": "NLConditionLogitNetworkStatusNode",
    "LogicNativeMouseWheel": "NLMouseDataParameter",
    "LogicNativeMouseRay": "NLActionMousePickNode",
    "LogicNativeMouseLook": "NLActionMouseLookNode",
    "LogicNativeKeyLogger": "NLKeyLoggerAction",
    "LogicNativeSetCursorVisibility": "NLActionSetMouseCursorVisibility",
    "LogicNativeSetCursorPosition": "NLActionSetMousePosition",
    "LogicNativeGamepadButton": "NLGamepadButtonsCondition",
    "LogicNativeGamepadStick": "NLGamepadSticksCondition",
    "LogicNativeSetGravity": "NLActionSetGravity",
    "LogicNativeGetCollisionGroup": "LogicNodeGetCollisionBitMask",
    "LogicNativeSetCollisionGroup": "NLSetCollisionGroup",
    "LogicNativeSetPhysics": "NLActionSetPhysicsNode",
    "LogicNativeSetDynamics": "NLActionSetDynamicsNode",
    "LogicNativeVehicleSetAttributes": "NLVehicleSetAttributes",
    "LogicNativeRaycast": "LogicNodeRaycast",
    "LogicNativeSendEvent": "NLActionCreateMessage",
    "LogicNativeReceiveEvent": "NLParameterReceiveMessage",
    "LogicNativeNavigate": "NLActionNavigate",
    "LogicNativeFollowPath": "NLActionFollowPath",
    "LogicNativeTranslate": "NLActionTranslate",
    "LogicNativeCameraRay": "NLActionCameraPickNode",
    "LogicNativeGetScene": "NLGetScene",
    "LogicNativeGetCollection": "NLGetCollectionNode",
    "LogicNativeGetCollectionObjects": "NLGetCollectionObjectsNode",
    "LogicNativeGetCollectionObjectNames": "NLGetCollectionObjectNamesNode",
    "LogicNativeSetCollectionVisibility": "NLActionSetCollectionVisibility",
    "LogicNativeSetOverlayCollection": "NLSetOverlayCollection",
    "LogicNativeRemoveOverlayCollection": "NLRemoveOverlayCollection",
    "LogicNativeRotateToward": "NLActionRotateTo",
    "LogicNativeSlowFollow": "NLSlowFollow",
    "LogicNativeReplaceMesh": "NLActionReplaceMesh",
    "LogicNativeSetTimescale": "NLActionSetTimeScale",
    "LogicNativeSetLightPower": "NLSetLightEnergyAction",
    "LogicNativeSetLightShadow": "NLSetLightShadowAction",
    "LogicNativeEvaluateCurve": "LogicNodeEvaluateCurve",
    "LogicNativeRandomFloat": "NLActionRandomFloat",
    "LogicNativeRandomInt": "NLActionRandomInteger",
    "LogicNativeRandomVector": "NLRandomVect",
    "LogicNativeCombineXYZW": "LogicNodeCombineXYZW",
    "LogicNativeResizeVector": "LogicNodeResizeVector",
    "LogicNativeXYZToMatrix": "NLParameterEulerToMatrixNode",
    "LogicNativeMatrixToXYZ": "NLParameterMatrixToEulerNode",
    "LogicNativeVectorRotate": "LogicNodeRotateByPoint",
    "LogicNativeFilePath": "LogicNodeFilePath",
    "LogicNativeGetSound": "NLGetSound",
    "LogicNativeGetImage": "NLGetImage",
    "LogicNativeGetFont": "LogicNodeGetFont",
    "LogicNativeGetObjectID": "LogicNodeGetObjectID",
    "LogicNativeGetAxisVector": "LogicNodeGetAxisVector",
    "LogicNativeDrawLine": "NLDrawLine",
    "LogicNativeDrawCube": "NLDrawCube",
    "LogicNativeDrawBox": "NLDrawBox",
    "LogicNativeDraw": "LogicNodeDraw",
    "LogicNativeJoinPath": "LogicNodeJoinPath",
    "LogicNativeGetMasterFolder": "LogicNodeGetMasterFolder",
    "LogicNativeFormula": "NLParameterMathFun",
    "LogicNativeTweenValue": "LogicNodeTweenValue",
    "LogicNativeSpawnPool": "LogicNodeSpawnPool",
    "LogicNativeAddPhysicsConstraint": "NLActionAddPhysicsConstraint",
    "LogicNativeRemovePhysicsConstraint": "NLActionRemovePhysicsConstraint",
    "LogicNativeProjectileRay": "NLProjectileRayCast",
    "LogicNativeValueBool": "NLParameterBooleanValue",
}

# Per-native expected addon socket *names* (subset of addon; native may use aliases).
EXPECTED_ADDON_SOCKETS: dict[str, tuple[dict[str, str], dict[str, str]]] = {
    **_PARITY_SOCKET_OVERRIDES,
    "LogicNativeGetGamePropertyFloat": (
        {"Object": "socket", "Property": "socket"},
        {"Property Value": "socket"},
    ),
    "LogicNativeGetGamePropertyInt": (
        {"Object": "socket", "Property": "socket"},
        {"Property Value": "socket"},
    ),
    "LogicNativeGetGamePropertyBool": (
        {"Object": "socket", "Property": "socket"},
        {"Property Value": "socket"},
    ),
    "LogicNativeGetGamePropertyString": (
        {"Object": "socket", "Property": "socket"},
        {"Property Value": "socket"},
    ),
    "LogicNativeSetGamePropertyFloat": (
        {"Condition": "socket", "Object": "socket", "Property": "socket"},
        {"Done": "socket"},
    ),
    "LogicNativeSetGamePropertyInt": (
        {"Condition": "socket", "Object": "socket", "Property": "socket"},
        {"Done": "socket"},
    ),
    "LogicNativeSetGamePropertyBool": (
        {"Condition": "socket", "Object": "socket", "Property": "socket"},
        {"Done": "socket"},
    ),
    "LogicNativeSetGamePropertyString": (
        {"Condition": "socket", "Object": "socket", "Property": "socket"},
        {"Done": "socket"},
    ),
    "LogicNativeToggleProperty": (
        {"Condition": "socket", "Object": "socket", "Property": "socket"},
        {"Done": "socket"},
    ),
    "LogicNativeHasProperty": (
        {"Object": "socket", "Name": "socket"},
        {"If True": "socket"},
    ),
    "LogicNativeOnInit": ({}, {"Out": "socket"}),
    "LogicNativeOnUpdate": ({}, {"Out": "socket"}),
    "LogicNativeOnNextFrame": ({}, {"Out": "socket"}),
    "LogicNativeTimer": (
        {"Set Timer": "socket", "Seconds": "socket"},
        {"When Elapsed": "socket"},
    ),
    "LogicNativeGateList": ({}, {"Result": "socket"}),
    "LogicNativeValueChanged": (
        {"Value": "socket"},
        {"If Changed": "socket", "Old": "socket", "New": "socket"},
    ),
    "LogicNativeStopAction": (
        {"Condition": "socket", "Object": "socket", "Animation Layer": "socket"},
        {"Done": "socket"},
    ),
    "LogicNativeMouseMoved": (
        {},
        {"If Moved": "socket"},
    ),
    "LogicNativeMouseWheel": (
        {},
        {"When Scrolled": "socket", "Difference": "socket"},
    ),
    "LogicNativeCursorPosition": (
        {},
        {"Position": "socket", "X": "socket", "Y": "socket"},
    ),
    "LogicNativeGamepadVibration": (
        {"Condition": "socket", "Index": "socket", "Left": "socket", "Right": "socket", "Time": "socket"},
        {"Done": "socket"},
    ),
    "LogicNativeGamepadLook": (
        {
            "Condition": "socket",
            "Body": "socket",
            "Head": "socket",
            "Inverted": "socket",
            "Index": "socket",
            "Sensitivity": "socket",
            "Exponent": "socket",
            "Cap Left / Right": "socket",
            "Cap Up / Down": "socket",
            "Threshold": "socket",
        },
        {"Done": "socket"},
    ),
    "LogicNativeMouseLook": (
        {
            "Condition": "socket",
            "Body": "socket",
            "Head": "socket",
            "Invert XY": "socket",
            "Sensitivity": "socket",
            "Cap Left / Right": "socket",
            "Cap Up / Down": "socket",
            "Smoothing": "socket",
        },
        {"Done": "socket"},
    ),
    "LogicNativeKeyLogger": (
        {"Only Characters": "socket"},
        {"Pressed": "socket", "Character": "socket", "Keycode": "socket"},
    ),
    "LogicNativeFollowPath": (
        {
            "Condition": "socket",
            "Moving Object": "socket",
            "Rotating Object": "socket",
            "Path Points": "socket",
            "Loop": "socket",
            "Continue": "socket",
            "Optional Navmesh": "socket",
            "Move as Dynamic": "socket",
            "Lin Speed": "socket",
            "Reach Threshold": "socket",
            "Look At": "socket",
            "Rot Speed": "socket",
            "Rot Axis": "socket",
            "Front": "socket",
        },
        {"Done": "socket"},
    ),
    "LogicNativeListFromItems": (
        {
            "Values": "socket",
            "Floats": "socket",
            "Integers": "socket",
            "Strings": "socket",
            "Booleans": "socket",
            "Vectors": "socket",
            "Colors": "socket",
            "Lists": "socket",
            "Dictionaries": "socket",
            "Datablocks": "socket",
            "Objects": "socket",
            "Collections": "socket",
            "Conditions": "socket",
            "Instances": "socket",
            "Widgets": "socket",
        },
        {
            "Values": "socket",
            "Floats": "socket",
            "Integers": "socket",
            "Strings": "socket",
            "Booleans": "socket",
            "Vectors": "socket",
            "Colors": "socket",
            "Lists": "socket",
            "Dictionaries": "socket",
            "Datablocks": "socket",
            "Objects": "socket",
            "Collections": "socket",
            "Conditions": "socket",
            "Instances": "socket",
            "Widgets": "socket",
        },
    ),
}

# Native snapshot getters with dedicated node coverage.
SNAPSHOT_ATTRIBUTE_NATIVE = frozenset({
    "LogicNativeGetGravity",
})

SNAPSHOT_OUTPUT_BY_NATIVE = {
    "LogicNativeGetGravity": {"Gravity"},
}

# Native display name may satisfy addon socket name (one direction only).
SOCKET_NAME_ALIASES: tuple[tuple[str, str], ...] = (
    ("Out", "If Pressed"),
    ("Out", "Pressed"),
    ("Out", "Pulse"),
    ("Out", "If Changed"),
    ("Out", "If True"),
    ("Out", "When Elapsed"),
    ("Out", "Done"),
    ("Out", "Result"),
    ("Out", "Running"),
    ("Out", "Hit"),
    ("Out", "Colliding Object"),
    ("Out", "Added Object"),
    ("Out", "Child"),
    ("Out", "Loop"),
    ("Out", "String"),
    ("Out", "Color"),
    ("Out", "Vector"),
    ("Out", "Rotation"),
    ("Out", "Position"),
    ("Out", "Movement"),
    ("Out", "Keys"),
    ("Out", "Item"),
    ("Out", "Element"),
    ("Out", "Dictionary"),
    ("Out", "List"),
    ("Out", "Time"),
    ("Out", "Factor"),
    ("Out", "Power"),
    ("Out", "Property"),
    ("Out", "Stored Value"),
    ("Value", "Property Value"),
    ("Value", "Float"),
    ("Value", "Int"),
    ("Value", "Bool"),
    ("Value", "String"),
    ("Value", "Vector"),
    ("Value", "Result"),
    ("Value", "LIST"),
    ("Value", "Color"),
    ("Value", "Visible"),
    ("Value", "Gravity"),
    ("Value", "Timescale"),
    ("Value", "Physics"),
    ("Value", "Dynamics"),
    ("Value", "Rigid Body"),
    ("Value", "Shadow"),
    ("VEC", "Vector"),
    ("Name", "Property"),
    ("Movement", "Vector"),
    ("Force", "Vector"),
    ("Torque", "Vector"),
    ("Impulse", "Vector"),
    ("Position", "Value"),
    ("Position", "Vector"),
    ("Orientation", "Value"),
    ("Scale", "Value"),
    ("Velocity", "Value"),
    ("Color", "Value"),
    ("Visible", "Value"),
    ("Object", "game_object"),
    ("Object", "Light Object"),
    ("Object", "Parent"),
    ("Object", "Copy From"),
    ("Object", "To"),
    ("Object", "Added Object"),
    ("Object", "Colliding Object"),
    ("Object", "Target"),
    ("Loop", "LOOP"),
    ("Position", "Vector"),
    ("Velocity", "Vector"),
    ("Rotation", "Orientation"),
    ("Rotation", "Value"),
    ("Scale", "Vector"),
    ("Gravity", "Vector"),
    ("Attribute", "Property"),
    ("Flow", "Condition"),
    ("Flow", "Set Timer"),
    ("Time", "Seconds"),
    ("Time", "Delay"),
    ("Layer", "Animation Layer"),
    ("Bone Name", "bone"),
    ("Mask", "Bitmask"),
    ("Group", "Bitmask"),
    ("Layers", "Bitmask"),
    ("X", "A"),
    ("Y", "B"),
    ("Z", "C"),
    ("Min", "Threshold"),
    ("Max", "Threshold"),
    ("Range", "Threshold"),
    ("Range", "Steps"),
    ("String", "A"),
    ("String", "B"),
    ("Format", "A"),
    ("Factor", "C"),
    ("Value", "Property"),
    ("Inverted", "Invert XY"),
    ("Interval", "Gap"),
    ("Recursive", "Include Children"),
    ("Euler", "Rotation"),
    ("If True", "Result"),
    ("Has Result", "Hit"),
    ("Hit Object", "Object"),
    ("Picked Object", "Object"),
    ("Point", "Position"),
    ("Caster", "Object"),
    ("Destination", "Direction"),
    ("Speaker", "Object"),
    ("Item A", "Items"),
    ("Item B", "Items"),
    ("Item C", "Items"),
    ("Index", "Parent"),
    ("Child Index", "Index"),
    ("Tree Name", "Tree"),
    ("Network", "Tree"),
    ("Message", "Event"),
    ("Subject", "Event"),
    ("True", "Out"),
    ("False", "Out"),
)


def addon_idname_for_native(native_idname: str, catalog_label: str):
    if native_idname in NATIVE_ONLY:
        return None
    if native_idname in NATIVE_TO_ADDON:
        return NATIVE_TO_ADDON[native_idname]
    return LABEL_TO_ADDON.get(catalog_label.strip().lower())


def native_satisfies_addon_name(native_names: set[str], addon_name: str) -> bool:
    if addon_name in native_names:
        return True
    for a, b in SOCKET_NAME_ALIASES:
        if addon_name == b and a in native_names:
            return True
        if addon_name == a and b in native_names:
            return True
    return False


def addon_inputs_satisfied(native_idname: str, native_in: set[str], addon_in: set[str]) -> bool:
    if native_idname == "LogicNativeGateList":
        native_cond = sum(1 for n in native_in if "condition" in n.lower())
        return native_cond >= 2
    if not addon_in:
        return True
    return all(native_satisfies_addon_name(native_in, name) for name in addon_in)


def addon_outputs_satisfied(native_in: set[str], native_out: set[str], addon_out: set[str]) -> bool:
    if not addon_out:
        return True
    return all(native_satisfies_addon_name(native_out, name) for name in addon_out)
