# SPDX-FileCopyrightText: 2026 UPBGE Authors
#
# SPDX-License-Identifier: GPL-2.0-or-later

LOGIC_NODE_STATUS_IMPLEMENTED = "implemented"
LOGIC_NODE_STATUS_DEFERRED = "deferred"
LOGIC_NODE_STATUS_DROPPED = "dropped"
LOGIC_NODE_STATUS_UNTRACKED = "untracked"


def _implemented(idname, label, menu_path, family, *, phase="Phase 4"):
    return {
        "idname": idname,
        "label": label,
        "menu_path": menu_path,
        "family": family,
        "status": LOGIC_NODE_STATUS_IMPLEMENTED,
        "visible": True,
        "phase": phase,
    }


def _deferred(key, label, family, reason, *, idname=None, target_phase="Phase 4 closure",
              infrastructure_blocker=None, menu_path=None):
    return {
        "key": key,
        "idname": idname,
        "label": label,
        "menu_path": menu_path,
        "family": family,
        "status": LOGIC_NODE_STATUS_DEFERRED,
        "visible": False,
        "phase": target_phase,
        "reason": reason,
        "infrastructure_blocker": infrastructure_blocker,
    }


def _dropped(key, label, family, reason, *, menu_path=None, target_phase="Phase 7"):
    return {
        "key": key,
        "idname": None,
        "label": label,
        "menu_path": menu_path,
        "family": family,
        "status": LOGIC_NODE_STATUS_DROPPED,
        "visible": False,
        "phase": target_phase,
        "reason": reason,
    }


_IMPLEMENTED_NATIVE_NODES = (
    _implemented("LogicNativeOnInit", "On Init", "Events", "Events/Logic/Time"),
    _implemented("LogicNativeOnUpdate", "On Update", "Events", "Events/Logic/Time"),
    _implemented("LogicNativeOnNextFrame", "On Next Frame", "Events", "Events/Logic/Time"),
    _implemented("LogicNativeOnce", "Do Once", "Events", "Events/Logic/Time"),
    _implemented("LogicNativeBooleanEdge", "Boolean Edge", "Events", "Events/Logic/Time"),
    _implemented("LogicNativeValueChanged", "On Value Changed", "Events", "Events/Logic/Time"),
    _implemented("LogicNativeValueChangedTo", "On Value Changed To", "Events", "Events/Logic/Time"),
    _implemented("LogicNativeBranch", "Branch", "Logic", "Events/Logic/Time"),
    _implemented("LogicNativeGate", "Gate", "Logic", "Events/Logic/Time"),
    _implemented("LogicNativeGateList", "Gate List", "Logic", "Events/Logic/Time"),
    _implemented("LogicNativeDelay", "Delay", "Time", "Events/Logic/Time"),
    _implemented("LogicNativeTimer", "Timer", "Time", "Events/Logic/Time"),
    _implemented("LogicNativeCooldown", "Cooldown", "Time", "Events/Logic/Time"),
    _implemented("LogicNativePulsify", "Pulsify", "Time", "Events/Logic/Time"),
    _implemented("LogicNativeBarrier", "Barrier", "Time", "Events/Logic/Time"),

    _implemented("LogicNativeValueBool", "Boolean", "Values", "Values/Math"),
    _implemented("LogicNativeValueInt", "Integer", "Values", "Values/Math"),
    _implemented("LogicNativeValueFloat", "Float", "Values", "Values/Math"),
    _implemented("LogicNativeValueString", "String", "Values", "Values/Math"),
    _implemented("LogicNativeValueVector", "Vector", "Values/Vector", "Values/Math"),
    _implemented("LogicNativeValueColor", "Color", "Values/Vector", "Values/Math"),
    _implemented("LogicNativeColorRGB", "Color RGB", "Values/Vector", "Values/Math"),
    _implemented("LogicNativeColorRGBA", "Color RGBA", "Values/Vector", "Values/Math"),
    _implemented("LogicNativeCombineXY", "Combine XY", "Values/Vector", "Values/Math"),
    _implemented("LogicNativeCombineXYZ", "Combine XYZ", "Values/Vector", "Values/Math"),
    _implemented("LogicNativeCombineXYZW", "Combine XYZW", "Values/Vector", "Values/Math", phase="Tier C"),
    _implemented("LogicNativeResizeVector", "Resize Vector", "Values/Vector", "Values/Math", phase="Tier C"),
    _implemented("LogicNativeXYZToMatrix", "XYZ to Matrix", "Values/Vector", "Values/Math", phase="Tier C"),
    _implemented("LogicNativeMatrixToXYZ", "Matrix to XYZ", "Values/Vector", "Values/Math", phase="Tier C"),
    _implemented("LogicNativeVectorRotate", "Vector Rotate", "Values/Vector", "Values/Math", phase="Tier C"),
    _implemented("LogicNativeSeparateXY", "Separate XY", "Values/Vector", "Values/Math"),
    _implemented("LogicNativeSeparateEuler", "Separate Euler", "Values/Vector", "Values/Math"),
    _implemented("LogicNativeSeparateXYZ", "Separate XYZ", "Values/Vector", "Values/Math"),
    _implemented("LogicNativeEuler", "Euler", "Values/Vector", "Values/Math"),
    _implemented("LogicNativeVectorToRotation", "Vector to Rotation", "Values/Vector", "Values/Math", phase="Tier C"),
    _implemented("LogicNativeRandomValue", "Random Value", "Values", "Values/Math"),
    _implemented("LogicNativeRandomFloat", "Random Float", "Values", "Values/Math", phase="Tier B"),
    _implemented("LogicNativeRandomInt", "Random Integer", "Values", "Values/Math", phase="Tier B"),
    _implemented("LogicNativeRandomVector", "Random Vector", "Values/Vector", "Values/Math", phase="Tier B"),
    _implemented("LogicNativeInvertValue", "Invert", "Values", "Values/Math"),
    _implemented("LogicNativeTypecast", "Typecast Value", "Values", "Values/Math", phase="Tier B"),
    _implemented("LogicNativeStringOperation", "String Operation", "Values", "Values/Math"),
    _implemented("LogicNativeFormattedString", "Formatted String", "Values", "Values/Math"),
    _implemented("LogicNativeStoreValue", "Store Value", "Values", "Values/Math"),
    _implemented("LogicNativeValueSwitch", "Value Switch", "Values", "Values/Math"),
    _implemented("LogicNativeValueSwitchList", "Value Switch List", "Values", "Values/Math", phase="Tier B"),
    _implemented("LogicNativeValueSwitchListCompare", "Value Switch List Compare", "Values", "Values/Math", phase="Tier B"),
    _implemented("LogicNativeValueValid", "Value Valid", "Logic", "Events/Logic/Time", phase="Tier B"),
    _implemented("LogicNativeNone", "None", "Logic", "Events/Logic/Time",
                 phase="Phase 4 closure"),
    _implemented("LogicNativeNotNone", "Not None", "Logic", "Events/Logic/Time",
                 phase="Phase 4 closure"),
    _implemented("LogicNativeMath", "Math", "Math", "Values/Math"),
    _implemented("LogicNativeVectorMath", "Vector Math", "Math", "Values/Math"),
    _implemented("LogicNativeClampValue", "Clamp", "Math", "Values/Math"),
    _implemented("LogicNativeMapRange", "Map Range", "Math", "Values/Math"),
    _implemented("LogicNativeCompare", "Compare", "Math", "Values/Math"),
    _implemented("LogicNativeThreshold", "Threshold", "Math", "Values/Math"),
    _implemented("LogicNativeRangedThreshold", "Ranged Threshold", "Math", "Values/Math"),
    _implemented("LogicNativeLimitRange", "Limit Range", "Values", "Values/Math"),
    _implemented("LogicNativeWithinRange", "Within Range", "Math", "Values/Math"),

    _implemented("LogicNativeHasProperty", "Has Property", "Values/Properties", "Properties/Object"),
    _implemented("LogicNativeEvaluateProperty", "Evaluate Object Property", "Values/Properties", "Properties/Object", phase="Tier B"),
    _implemented("LogicNativeGetGamePropertyFloat", "Get Object Property (Float)",
                 "Values/Properties", "Properties/Object"),
    _implemented("LogicNativeGetGamePropertyInt", "Get Object Property (Integer)",
                 "Values/Properties", "Properties/Object"),
    _implemented("LogicNativeGetGamePropertyBool", "Get Object Property (Boolean)",
                 "Values/Properties", "Properties/Object"),
    _implemented("LogicNativeGetGamePropertyString", "Get Object Property (String)",
                 "Values/Properties", "Properties/Object"),
    _implemented("LogicNativeSetGamePropertyFloat", "Set Object Property (Float)",
                 "Values/Properties", "Properties/Object"),
    _implemented("LogicNativeSetGamePropertyInt", "Set Object Property (Integer)",
                 "Values/Properties", "Properties/Object"),
    _implemented("LogicNativeSetGamePropertyBool", "Set Object Property (Boolean)",
                 "Values/Properties", "Properties/Object"),
    _implemented("LogicNativeSetGamePropertyString", "Set Object Property (String)",
                 "Values/Properties", "Properties/Object"),
    _implemented("LogicNativeToggleProperty", "Toggle Property", "Values/Properties",
                 "Properties/Object"),
    _implemented("LogicNativeModifyProperty", "Modify Property", "Values/Properties",
                 "Properties/Object"),
    _implemented("LogicNativeModifyPropertyClamped", "Modify Property Clamped",
                 "Values/Properties", "Properties/Object"),
    _implemented("LogicNativeGetTreeProperty", "Get Tree Property", "Values/Properties",
                 "Properties/Object", phase="Phase 4 closure"),
    _implemented("LogicNativeSetTreeProperty", "Set Tree Property", "Values/Properties",
                 "Properties/Object", phase="Phase 4 closure"),
    _implemented("LogicNativeToggleTreeProperty", "Toggle Tree Property", "Values/Properties",
                 "Properties/Object", phase="Tier B"),
    _implemented("LogicNativeGetGlobalProperty", "Get Global Property", "Values/Properties",
                 "Properties", phase="Tier A"),
    _implemented("LogicNativeSetGlobalProperty", "Set Global Property", "Values/Properties",
                 "Properties", phase="Tier A"),
    _implemented("LogicNativeListGlobalProperties", "List Global Properties", "Values/Properties",
                 "Properties", phase="Tier A"),
    _implemented("LogicNativeLoadVariable", "Load Variable", "Values/Properties",
                 "Properties", phase="Tier A"),
    _implemented("LogicNativeSaveVariable", "Save Variable", "Values/Properties",
                 "Properties", phase="Tier A"),
    _implemented("LogicNativeLoadVariableDict", "Load Variable Dict", "Values/Properties",
                 "Properties", phase="Tier A"),
    _implemented("LogicNativeSaveVariableDict", "Save Variable Dict", "Values/Properties",
                 "Properties", phase="Tier A"),
    _implemented("LogicNativeClearVariables", "Clear Variables", "Values/Properties",
                 "Properties", phase="Tier B"),
    _implemented("LogicNativeListSavedVariables", "List Saved Variables", "Values/Properties",
                 "Properties", phase="Tier B"),
    _implemented("LogicNativeRemoveVariable", "Remove Variable", "Values/Properties",
                 "Properties", phase="Tier B"),
    _implemented("LogicNativeApplyMovement", "Apply Movement", "Objects/Transformation",
                 "Properties/Object/Transform"),
    _implemented("LogicNativeApplyRotation", "Apply Rotation", "Objects/Transformation",
                 "Properties/Object/Transform"),
    _implemented("LogicNativeApplyForce", "Apply Force", "Objects/Transformation",
                 "Properties/Object/Transform"),
    _implemented("LogicNativeApplyForceToTarget", "Apply Force To Target",
                 "Objects/Transformation", "Properties/Object/Transform"),
    _implemented("LogicNativeApplyTorque", "Apply Torque", "Objects/Transformation",
                 "Properties/Object/Transform"),
    _implemented("LogicNativeApplyImpulse", "Apply Impulse", "Objects/Transformation",
                 "Properties/Object/Transform"),
    _implemented("LogicNativeFindObject", "Get Object", "Objects/Object Data",
                 "Properties/Object/Transform", phase="Tier A"),
    _implemented("LogicNativeObjectByName", "Get Object By Name", "Objects/Object Data",
                 "Properties/Object/Transform", phase="Tier A"),
    _implemented("LogicNativeGetOwner", "Get Owner", "Objects/Object Data",
                 "Properties/Object/Transform", phase="Tier A"),
    _implemented("LogicNativeGetDistance", "Get Distance", "Objects/Object Data",
                 "Properties/Object/Transform"),
    _implemented("LogicNativeGetGroupCenterPosition", "Get Group Center position",
                 "Objects/Object Data", "Properties/Object/Transform"),
    _implemented("LogicNativeAddObject", "Add Object", "Objects/Object Data",
                 "Properties/Object/Transform"),
    _implemented("LogicNativeSetParent", "Set Parent", "Objects/Object Data",
                 "Properties/Object/Transform"),
    _implemented("LogicNativeGetParent", "Get Parent", "Objects/Object Data",
                 "Properties/Object/Transform", phase="Phase 4 closure"),
    _implemented("LogicNativeGetChild", "Get Child", "Objects/Object Data",
                 "Properties/Object/Transform", phase="Phase 4 closure"),
    _implemented("LogicNativeGetChildByName", "Get Child By Name", "Objects/Object Data",
                 "Properties/Object/Transform", phase="Tier B"),
    _implemented("LogicNativeRemoveParent", "Remove Parent", "Objects/Object Data",
                 "Properties/Object/Transform"),
    _implemented("LogicNativeRemoveObject", "Remove Object", "Objects/Object Data",
                 "Properties/Object/Transform"),

    _implemented("LogicNativeKeyboardKey", "Keyboard Key", "Input/Keyboard", "Input"),
    _implemented("LogicNativeKeyboardActive", "Keyboard Active", "Input/Keyboard", "Input",
                 phase="Phase 4 closure"),
    _implemented("LogicNativeKeyCode", "Key Code", "Input/Keyboard", "Input",
                 phase="Phase 4 closure"),
    _implemented("LogicNativeMouseButton", "Mouse Button", "Input/Mouse", "Input"),
    _implemented("LogicNativeMouseMoved", "Mouse Moved", "Input/Mouse", "Input",
                 phase="Phase 4 closure"),
    _implemented("LogicNativeMouseWheel", "Mouse Wheel", "Input/Mouse", "Input",
                 phase="Phase 4 closure"),
    _implemented("LogicNativeMouseOver", "Mouse Over", "Input/Mouse", "Input",
                 phase="Phase 4 closure"),
    _implemented("LogicNativeMouseRay", "Mouse Ray", "Input/Mouse", "Input", phase="Tier A"),
    _implemented("LogicNativeCursorPosition", "Cursor Position", "Input/Mouse", "Input",
                 phase="Phase 4 closure"),
    _implemented("LogicNativeCursorMovement", "Cursor Movement", "Input/Mouse", "Input",
                 phase="Phase 4 closure"),
    _implemented("LogicNativeSetCursorVisibility", "Set Cursor Visibility", "Input/Mouse",
                 "Input", phase="Phase 4 closure"),
    _implemented("LogicNativeSetCursorPosition", "Set Cursor Position", "Input/Mouse",
                 "Input", phase="Phase 4 closure"),
    _implemented("LogicNativeMouseLook", "Mouse Look", "Input/Mouse", "Input"),
    _implemented("LogicNativeKeyLogger", "Key Logger", "Input/Keyboard", "Input"),
    _implemented("LogicNativeGamepadButton", "Gamepad Button", "Input/Gamepad", "Input",
                 phase="Phase 4 closure"),
    _implemented("LogicNativeGamepadStick", "Gamepad Sticks", "Input/Gamepad", "Input",
                 phase="Phase 4 closure"),
    _implemented("LogicNativeGamepadActive", "Gamepad Active", "Input/Gamepad", "Input",
                 phase="Phase 4 closure"),
    _implemented("LogicNativeGamepadVibration", "Gamepad Vibration", "Input/Gamepad", "Input",
                 phase="Phase 4 closure"),
    _implemented("LogicNativeGamepadLook", "Gamepad Look", "Input/Gamepad", "Input",
                 phase="Phase 4 closure"),

    _implemented("LogicNativeGetGravity", "Get Gravity", "Physics", "Physics/Jolt",
                 phase="Phase 5"),
    _implemented("LogicNativeSetGravity", "Set Gravity", "Physics", "Physics/Jolt",
                 phase="Phase 5"),
    _implemented("LogicNativeGetCollisionGroup", "Get Collision Layers", "Physics",
                 "Physics/Jolt", phase="Phase 5"),
    _implemented("LogicNativeSetCollisionGroup", "Set Collision Layers", "Physics",
                 "Physics/Jolt", phase="Phase 5"),
    _implemented("LogicNativeSetPhysics", "Enable Physics Body", "Physics", "Physics/Jolt",
                 phase="Phase 5"),
    _implemented("LogicNativeSetDynamics", "Set Dynamics", "Physics", "Physics/Jolt",
                 phase="Phase 5"),
    _implemented("LogicNativeRebuildCollisionShape", "Rebuild Collision Shape", "Physics",
                 "Physics/Jolt", phase="Phase 5"),
    _implemented("LogicNativeGetRigidBodyAttribute", "Get Rigid Body Attribute", "Physics",
                 "Physics/Jolt", phase="Phase 5"),
    _implemented("LogicNativeSetRigidBodyAttribute", "Set Rigid Body Attribute", "Physics",
                 "Physics/Jolt", phase="Phase 5"),
    _implemented("LogicNativeGetCharacterInfo", "Get Physics Info", "Physics/Character",
                 "Physics/Jolt", phase="Phase 5 closure"),
    _implemented("LogicNativeCharacterJump", "Jump", "Physics/Character", "Physics/Jolt",
                 phase="Phase 5 closure"),
    _implemented("LogicNativeSetCharacterGravity", "Set Gravity", "Physics/Character",
                 "Physics/Jolt", phase="Phase 5 closure"),
    _implemented("LogicNativeSetCharacterJumpSpeed", "Set Jump Force", "Physics/Character",
                 "Physics/Jolt", phase="Phase 5 closure"),
    _implemented("LogicNativeSetCharacterMaxJumps", "Set Max Jumps", "Physics/Character",
                 "Physics/Jolt", phase="Phase 5 closure"),
    _implemented("LogicNativeSetCharacterWalkDirection", "Walk", "Physics/Character",
                 "Physics/Jolt", phase="Phase 5 closure"),
    _implemented("LogicNativeSetCharacterVelocity", "Set Velocity", "Physics/Character",
                 "Physics/Jolt", phase="Phase 5 closure"),
    _implemented("LogicNativeVehicleControl", "Vehicle Control", "Physics/Vehicle",
                 "Physics/Jolt", phase="Phase 5 closure"),
    _implemented("LogicNativeVehicleAccelerate", "Accelerate", "Physics/Vehicle",
                 "Physics/Jolt", phase="Phase 5 closure"),
    _implemented("LogicNativeVehicleBrake", "Brake", "Physics/Vehicle",
                 "Physics/Jolt", phase="Phase 5 closure"),
    _implemented("LogicNativeVehicleSetAttributes", "Set Vehicle Attributes",
                 "Physics/Vehicle", "Physics/Jolt", phase="Phase 5 closure"),
    _implemented("LogicNativeVehicleSteer", "Steer", "Physics/Vehicle",
                 "Physics/Jolt", phase="Phase 5 closure"),
    _implemented("LogicNativeRaycast", "Raycast", "Physics", "Physics/Jolt",
                 phase="Phase 5 closure"),
    _implemented("LogicNativeRaycastAll", "Raycast All", "Physics", "Physics/Jolt",
                 phase="Phase 5 closure"),
    _implemented("LogicNativeShapeCast", "Shape Cast", "Physics", "Physics/Jolt",
                 phase="Phase 5 closure"),
    _implemented("LogicNativeShapeCastAll", "Shape Cast All", "Physics", "Physics/Jolt",
                 phase="Phase 5 closure"),
    _implemented("LogicNativeObjectsColliding", "Objects Colliding", "Physics", "Physics/Jolt",
                 phase="Phase 5 closure"),
    _implemented("LogicNativePlayAction", "Play Action", "Animation", "Animation/Actions",
                 phase="Phase 5 closure"),
    _implemented("LogicNativeStopAction", "Stop Action", "Animation", "Animation/Actions",
                 phase="Phase 5 closure"),
    _implemented("LogicNativeSetActionFrame", "Set Action Frame", "Animation", "Animation/Actions",
                 phase="Phase 5 closure"),
    _implemented("LogicNativeActionDone", "Action Done", "Animation", "Animation/Actions",
                 phase="Phase 5 closure"),
    _implemented("LogicNativeGetBoneHeadWorld", "Get Rest Bone Head", "Animation/Get Rest Bone Data",
                 "Animation", phase="Phase 5 closure"),
    _implemented("LogicNativeStopAllSounds", "Stop All Sounds", "Sound", "Sound",
                 phase="Phase 5 closure"),
    _implemented("LogicNativePlaySound", "Play Sound", "Sound", "Sound",
                 phase="Phase 5 closure"),
    _implemented("LogicNativeStopSound", "Stop Sound", "Sound", "Sound",
                 phase="Phase 5 closure"),
    _implemented("LogicNativePlaySound3D", "Play Sound 3D", "Sound", "Sound",
                 phase="Phase 5 closure"),
    _implemented("LogicNativePauseSound", "Pause Sound", "Sound", "Sound",
                 phase="Phase 5 closure"),
    _implemented("LogicNativeResumeSound", "Resume Sound", "Sound", "Sound",
                 phase="Phase 5 closure"),
    _implemented("LogicNativeSetBonePoseRotation", "Set Pose Bone Rotation",
                 "Animation/Set Pose Bone Data", "Animation",
                 phase="Phase 5 closure"),
    _implemented("LogicNativeSetBoneConstraintInfluence", "Set Constraint Influence",
                 "Animation/Bone Constraints", "Animation",
                 phase="Phase 5 closure"),
    _implemented("LogicNativeSetMaterialSlot", "Assign Material To Slot", "Nodes/Materials", "Nodes",
                 phase="Phase 5 closure"),
    _implemented("LogicNativeSetMaterialParameter", "Set Material Parameter", "Nodes/Materials", "Nodes",
                 phase="Phase 5 closure"),
    _implemented("LogicNativeEvaluateCurve", "Evaluate Curve", "Objects/Curves", "Objects",
                 phase="Phase 5 closure"),
    _implemented("LogicNativeGetTimescale", "Get Timescale", "Scene", "Scene/Camera/Render",
                 phase="Phase 5"),
    _implemented("LogicNativeTime", "Time", "Time", "Time",
                 phase="Phase 1"),
    _implemented("LogicNativeDeltaFactor", "Delta Factor", "Time", "Time",
                 phase="Phase 1"),
    _implemented("LogicNativeQuitGame", "Quit Game", "Game", "Game",
                 phase="Phase 2"),
    _implemented("LogicNativeRestartGame", "Restart Game", "Game", "Game",
                 phase="Phase 2"),
    _implemented("LogicNativeLoadBlendFile", "Load Blender File", "Game", "Game",
                 phase="Phase 2"),
    _implemented("LogicNativeStartLogicTree", "Start Logic Tree", "Logic/Trees", "Logic",
                 phase="Phase 4"),
    _implemented("LogicNativeStopLogicTree", "Stop Logic Tree", "Logic/Trees", "Logic",
                 phase="Phase 4"),
    _implemented("LogicNativeRunLogicTree", "Run Logic Tree", "Logic/Trees", "Logic",
                 phase="Phase 4"),
    _implemented("LogicNativeInstallLogicTree", "Install Logic Tree", "Logic/Trees", "Logic",
                 phase="Phase 4"),
    _implemented("LogicNativeLogicTreeStatus", "Logic Tree Status", "Logic/Trees", "Logic",
                 phase="Phase 4"),
    _implemented("LogicNativeSetTimescale", "Set Timescale", "Scene", "Scene/Camera/Render",
                 phase="Phase 5"),
    _implemented("LogicNativeGetActiveCamera", "Active Camera", "Scene/Camera",
                 "Scene/Camera/Render", phase="Phase 5 closure"),
    _implemented("LogicNativeSetCamera", "Set Camera", "Scene/Camera",
                 "Scene/Camera/Render", phase="Phase 5 closure"),
    _implemented("LogicNativeSetCameraFov", "Set FOV", "Scene/Camera",
                 "Scene/Camera/Render", phase="Phase 5 closure"),
    _implemented("LogicNativeSetCameraOrthoScale", "Set Orthographic Scale",
                 "Scene/Camera", "Scene/Camera/Render", phase="Phase 5 closure"),
    _implemented("LogicNativeWorldToScreen", "World To Screen", "Scene/Camera",
                 "Scene/Camera/Render", phase="Phase 5 closure"),
    _implemented("LogicNativeScreenToWorld", "Screen To World", "Scene/Camera",
                 "Scene/Camera/Render", phase="Phase 5 closure"),
    _implemented("LogicNativeGetLightColor", "Get Light Color", "Lights", "Lights",
                 phase="Phase 5 closure"),
    _implemented("LogicNativeGetLightPower", "Get Light Power", "Lights", "Lights",
                 phase="Phase 5 closure"),
    _implemented("LogicNativeSetLightColor", "Set Light Color", "Lights", "Lights",
                 phase="Phase 5 closure"),
    _implemented("LogicNativeSetLightPower", "Set Light Power", "Lights", "Lights",
                 phase="Phase 5 closure"),
    _implemented("LogicNativeSetLightShadow", "Set Light Shadow", "Lights", "Lights",
                 phase="Phase 5 closure"),
    _implemented("LogicNativeMakeLightUnique", "Make Light Unique", "Lights", "Lights",
                 phase="Phase 5 closure"),
    _implemented("LogicNativeGetFullscreen", "Get Fullscreen", "Render",
                 "Scene/Camera/Render", phase="Phase 5 closure"),
    _implemented("LogicNativeSetFullscreen", "Set Fullscreen", "Render",
                 "Scene/Camera/Render", phase="Phase 5 closure"),
    _implemented("LogicNativeGetResolution", "Get Resolution", "Render",
                 "Scene/Camera/Render", phase="Phase 5 closure"),
    _implemented("LogicNativeSetResolution", "Set Resolution", "Render",
                 "Scene/Camera/Render", phase="Phase 5 closure"),
    _implemented("LogicNativeGetVSync", "Get VSync", "Render",
                 "Scene/Camera/Render", phase="Phase 5 closure"),
    _implemented("LogicNativeSetVSync", "Set VSync", "Render",
                 "Scene/Camera/Render", phase="Phase 5 closure"),
    _implemented("LogicNativeShowFramerate", "Show Framerate", "Render",
                 "Scene/Camera/Render", phase="Phase 5 closure"),
    _implemented("LogicNativeShowProfile", "Show Profile", "Render",
                 "Scene/Camera/Render", phase="Phase 5 closure"),
    _implemented("LogicNativePrint", "Print", "Utility", "Utility"),

    # Phase 6: New nodes.
    _implemented("LogicNativeSendEvent", "Send Event", "Events", "Events"),
    _implemented("LogicNativeReceiveEvent", "Receive Event", "Events", "Events"),
    _implemented("LogicNativeOnCollision", "On Collision", "Events", "Events"),
    _implemented("LogicNativeCollision", "Is Colliding", "Logic", "Logic"),
    _implemented("LogicNativeAnimationStatus", "Animation Status", "Animation/Actions", "Animation"),
    _implemented("LogicNativeMoveToward", "Move To", "Objects/Transformation", "Objects"),
    _implemented("LogicNativeNavigate", "Navigate", "Objects/Transformation", "Objects", phase="Tier A"),
    _implemented("LogicNativeFollowPath", "Follow Path", "Objects/Transformation", "Objects", phase="Tier A"),
    _implemented("LogicNativeTranslate", "Translate", "Objects/Transformation", "Objects", phase="Tier A"),
    _implemented("LogicNativeRotateToward", "Rotate To", "Objects/Transformation", "Objects"),
    _implemented("LogicNativeSlowFollow", "Slow Follow", "Objects/Transformation", "Objects"),
    _implemented("LogicNativeAlignAxisToVector", "Align Axis to Vector", "Objects/Transformation", "Objects"),
    _implemented("LogicNativeSetObjectAttribute", "Set Attribute", "Objects/Set Attribute", "Objects"),
    _implemented("LogicNativeReplaceMesh", "Replace Mesh", "Objects/Object Data", "Objects"),
    _implemented("LogicNativeGetObjectAttribute", "Get Object Attribute", "Objects/Get Attribute", "Objects"),
    _implemented("LogicNativeGetObjectID", "Get Object ID", "Objects/Get Attribute", "Objects", phase="Tier C"),
    _implemented("LogicNativeGetAxisVector", "Get Axis Vector", "Objects/Get Attribute", "Objects", phase="Tier C"),
    _implemented("LogicNativeLoadScene", "Load Scene", "Scene", "Scene"),
    _implemented("LogicNativeSetScene", "Set Scene", "Scene", "Scene"),
    _implemented("LogicNativeGetScene", "Get Scene", "Scene", "Scene", phase="Tier A"),
    _implemented("LogicNativeCameraRay", "Camera Ray", "Scene/Camera", "Scene/Camera", phase="Tier A"),
    _implemented("LogicNativeGetCollection", "Get Collection", "Scene/Collections", "Scene", phase="Tier A"),
    _implemented("LogicNativeGetCollectionObjects", "Get Collection Objects", "Scene/Collections", "Scene", phase="Tier A"),
    _implemented("LogicNativeGetCollectionObjectNames", "Get Collection Object Names", "Scene/Collections", "Scene", phase="Tier A"),
    _implemented("LogicNativeSetCollectionVisibility", "Set Collection Visibility", "Scene/Collections", "Scene", phase="Tier A"),
    _implemented("LogicNativeSetOverlayCollection", "Set Overlay Collection", "Scene/Collections", "Scene", phase="Tier B"),
    _implemented("LogicNativeRemoveOverlayCollection", "Remove Overlay Collection", "Scene/Collections", "Scene", phase="Tier B"),
    _implemented("LogicNativeSaveGame", "Save Game", "Game", "Game"),
    _implemented("LogicNativeLoadGame", "Load Game", "Game", "Game"),
    _implemented("LogicNativeCopyProperty", "Copy Property", "Values/Properties", "Properties"),

    _implemented("LogicNativeLoop", "Loop", "Logic/Loops", "Logic"),
    _implemented("LogicNativeLoopFromList", "Loop From List", "Data/List", "Data"),
    _implemented("LogicNativeListLength", "List Length", "Data/List", "Data"),
    _implemented("LogicNativeListGetItem", "List Get Item", "Data/List", "Data"),
    _implemented("LogicNativeListRandomItem", "Get Random List Item", "Data/List", "Data", phase="Tier B"),
    _implemented("LogicNativeFormula", "Formula", "Math", "Values/Math", phase="Tier B"),
    _implemented("LogicNativeTweenValue", "Tween Value", "Time", "Values/Math", phase="Tier B"),
    _implemented("LogicNativeSpawnPool", "Spawn Pool", "Objects/Object Data", "Objects", phase="Tier B"),
    _implemented("LogicNativeAddPhysicsConstraint", "Add Rigid Body Constraints", "Physics", "Physics", phase="Tier B"),
    _implemented("LogicNativeGetRigidBodyConstraints", "Get Rigid Body Constraints", "Physics", "Physics", phase="Tier B"),
    _implemented("LogicNativeRemovePhysicsConstraint", "Remove Rigid Body Constraints", "Physics", "Physics", phase="Tier B"),
    _implemented("LogicNativeProjectileRay", "Projectile Ray", "Physics", "Physics", phase="Tier B"),
    _implemented("LogicNativeMakeList", "Make List", "Data/List", "Data"),
    _implemented("LogicNativeListExtend", "Extend List", "Data/List", "Data"),
    _implemented("LogicNativeDictGetKey", "Get Dictionary Key", "Data/Dict", "Data"),
    _implemented("LogicNativeMakeDict", "Make Dictionary", "Data/Dict", "Data"),
    _implemented("LogicNativeDictLength", "Dictionary Length", "Data/Dict", "Data"),
    _implemented("LogicNativeDictGetKeys", "Get Dictionary Keys", "Data/Dict", "Data"),
    _implemented("LogicNativeGetBoneTailWorld", "Get Rest Bone Tail", "Animation/Get Rest Bone Data",
                 "Animation"),
    _implemented("LogicNativeGetBoneLength", "Get Rest Bone Length", "Animation/Get Rest Bone Data",
                 "Animation"),
    _implemented("LogicNativeGetBoneCenterWorld", "Get Rest Bone Center",
                 "Animation/Get Rest Bone Data", "Animation"),
    _implemented("LogicNativeGetBoneHeadPoseWorld", "Get Pose Bone Head",
                 "Animation/Get Pose Bone Data", "Animation"),
    _implemented("LogicNativeGetBoneTailPoseWorld", "Get Pose Bone Tail",
                 "Animation/Get Pose Bone Data", "Animation"),
    _implemented("LogicNativeGetBoneCenterPoseWorld", "Get Pose Bone Center",
                 "Animation/Get Pose Bone Data", "Animation"),
    _implemented("LogicNativeGetBonePoseRotation", "Get Pose Bone Rotation",
                 "Animation/Get Pose Bone Data", "Animation"),
    _implemented("LogicNativeGetBonePoseScale", "Get Pose Bone Scale",
                 "Animation/Get Pose Bone Data", "Animation"),
    _implemented("LogicNativeGetBonePoseTransform", "Get Pose Bone Transform",
                 "Animation/Get Pose Bone Data", "Animation"),
    _implemented("LogicNativeSetBonePoseLocation", "Set Pose Bone Location",
                 "Animation/Set Pose Bone Data", "Animation"),
    _implemented("LogicNativeSetBonePoseScale", "Set Pose Bone Scale",
                 "Animation/Set Pose Bone Data", "Animation"),
    _implemented("LogicNativeSetBonePoseTransform", "Set Pose Bone Transform",
                 "Animation/Set Pose Bone Data", "Animation"),
    _implemented("LogicNativeGetBoneAttribute", "Get Bone Attribute", "Animation/Advanced Bone Data", "Animation", phase="Tier C"),
    _implemented("LogicNativeSetBoneAttribute", "Set Bone Attribute", "Animation/Advanced Bone Data", "Animation", phase="Tier C"),
    _implemented("LogicNativeSetBoneConstraintTarget", "Set Constraint Target", "Animation/Bone Constraints", "Animation", phase="Tier C"),
    _implemented("LogicNativeSetBoneConstraintAttribute", "Set Constraint Attribute", "Animation/Bone Constraints", "Animation", phase="Tier C"),
    _implemented("LogicNativeListContains", "List Contains", "Data/List", "Data"),
    _implemented("LogicNativeEmptyList", "New List", "Data/List", "Data"),
    _implemented("LogicNativeEmptyDict", "New Dictionary", "Data/Dict", "Data"),
    _implemented("LogicNativeDictHasKey", "Dictionary Has Key", "Data/Dict", "Data"),
    _implemented("LogicNativeListDuplicate", "Duplicate List", "Data/List", "Data"),
    _implemented("LogicNativeDictMerge", "Merge Dictionaries", "Data/Dict", "Data"),
    _implemented("LogicNativeListAppend", "Append", "Data/List", "Data", phase="Tier A"),
    _implemented("LogicNativeListRemoveIndex", "Remove Index", "Data/List", "Data", phase="Tier A"),
    _implemented("LogicNativeListRemoveValue", "Remove Value", "Data/List", "Data", phase="Tier A"),
    _implemented("LogicNativeListSetIndex", "Set List Index", "Data/List", "Data", phase="Tier A"),
    _implemented("LogicNativeDictSetKey", "Set Dictionary Key", "Data/Dict", "Data", phase="Tier A"),
    _implemented("LogicNativeDictRemoveKey", "Remove Dictionary Key", "Data/Dict", "Data", phase="Tier A"),
    _implemented("LogicNativeListFromItems", "List From Items", "Data/List", "Data", phase="Tier A"),

    _implemented("LogicNativeGetMaterialFromSlot", "Get Material From Slot", "Nodes/Materials", "Nodes", phase="Tier C"),
    _implemented("LogicNativeGetMaterialSlotCount", "Get Material Slot Count", "Nodes/Materials", "Nodes", phase="Tier C"),
    _implemented("LogicNativeGetMaterialName", "Get Material Name", "Nodes/Materials", "Nodes", phase="Tier C"),
    _implemented("LogicNativeGetMaterialParameter", "Get Material Parameter", "Nodes/Materials", "Nodes", phase="Tier C"),
    _implemented("LogicNativeSetGeometryNodesInput", "Set Geometry Nodes Input", "Nodes/Geometry", "Nodes", phase="Tier C"),
    _implemented("LogicNativeGetEditorNodeValue", "Get Editor Node Value", "Nodes", "Nodes", phase="Tier C"),
    _implemented("LogicNativeSetEditorNodeValue", "Set Editor Node Value", "Nodes", "Nodes", phase="Tier C"),
    _implemented("LogicNativeMakeNodeTreeUnique", "Make Node Tree Unique", "Nodes", "Nodes", phase="Tier C"),
    _implemented("LogicNativeSetNodeMute", "Set Node Mute", "Nodes", "Nodes", phase="Tier C"),
    _implemented("LogicNativeEnableDisableModifier", "Enable or Disable Modifier", "Nodes/Geometry", "Nodes", phase="Tier C"),
    _implemented("LogicNativeAssignGeometryNodesModifier", "Assign Geometry Nodes Modifier", "Nodes/Geometry", "Nodes", phase="Tier C"),
    _implemented("LogicNativeGetSound", "Get Sound", "Sound", "Sound", phase="Tier C"),
    _implemented("LogicNativeGetImage", "Get Image", "File", "File", phase="Tier C"),
    _implemented("LogicNativeGetFont", "Get Font", "UI", "UI", phase="Tier C"),
    _implemented("LogicNativeDrawLine", "Draw Line", "Render", "Render", phase="Tier C"),
    _implemented("LogicNativeDrawCube", "Draw Cube", "Render", "Render", phase="Tier C"),
    _implemented("LogicNativeDrawBox", "Draw Box", "Render", "Render", phase="Tier C"),
    _implemented("LogicNativeDraw", "Draw", "Render", "Render", phase="Tier C"),
    _implemented("LogicNativeFilePath", "File Path", "Data/Path", "Data", phase="Tier C"),
    _implemented("LogicNativeJoinPath", "Join Path", "Data/Path", "Data", phase="Tier C"),
    _implemented("LogicNativeGetMasterFolder", "Get Master Folder", "Data/Path", "Data", phase="Tier C"),
)


_DEFERRED_PHASE4_NODES = (
    _deferred("nodes.material.play_sequence", "Play Material Sequence", "Nodes",
              "Material sequence playback needs a native image-sequence scheduler before it can "
              "match the Python addon behavior.",
              idname="LogicNativePlayMaterialSequence", target_phase="Future",
              menu_path="Nodes/Materials"),
    _deferred("nodes.group.get_socket", "Get Node Group Socket", "Nodes",
              "Node group socket access needs native group-instance resolution before parity can be "
              "claimed.",
              idname="LogicNativeGetNodeGroupSocketValue", target_phase="Future",
              menu_path="Nodes/Groups"),
    _deferred("nodes.group.set_socket", "Set Node Group Socket", "Nodes",
              "Node group socket writes need native group-instance resolution and update tagging.",
              idname="LogicNativeSetNodeGroupSocketValue", target_phase="Future",
              menu_path="Nodes/Groups"),
    _deferred("file.load_content", "Load File Content", "File",
              "File IO requires an explicit runtime policy and async/error behavior before parity.",
              idname="LogicNativeLoadFileContent", target_phase="Future", menu_path="File"),
    _deferred("sound.start_speaker", "Start Speaker", "Sound",
              "Speaker playback is partially compiled through the 3D sound path, but parity still "
              "needs occlusion, lowpass/transition behavior, finished-event flow, and sound-handle "
              "outputs.",
              idname="LogicNativeStartSpeaker", target_phase="Future", menu_path="Sound"),
    _deferred("ui.set_custom_cursor", "Set Custom Cursor", "UI",
              "Custom cursors need platform/window-manager integration beyond the existing cursor "
              "visibility and position commands.",
              idname="LogicNativeSetCustomCursor", target_phase="Future", menu_path="UI/Widgets"),
)


_DEFERRED_PHASE7_LOOPS_NODES = ()

_DROPPED_PHASE7_NODES = (
    _dropped(
        "input.vr",
        "VR Input",
        "Input/VR",
        "OpenXR/VR device input is out of scope for the current native roadmap.",
        menu_path="Input/VR",
    ),
    _dropped(
        "sound.fmod",
        "FMOD Sound",
        "Sound/FMOD",
        "FMOD integration is not part of the native audaspace-based sound stack.",
        menu_path="Sound/FMOD",
    ),
    _dropped(
        "network.lan",
        "Network",
        "Network",
        "LAN/network messaging nodes require a native networking subsystem and security policy.",
        menu_path="Network",
    ),
)

_DEFERRED_PHASE5_NODES = (
    _deferred("physics.vehicle.create", "Create New Vehicle", "Physics/Jolt",
              "Vehicle throttle/brake/steer/control nodes match logic-brick actuators; authoring a "
              "brand-new native vehicle still needs a safe runtime construction path.",
              target_phase="Future",
              infrastructure_blocker="3J"),
)


_TRACKED_NATIVE_NODES = (
    *_IMPLEMENTED_NATIVE_NODES,
    *_DEFERRED_PHASE4_NODES,
    *_DEFERRED_PHASE5_NODES,
    *_DEFERRED_PHASE7_LOOPS_NODES,
    *_DROPPED_PHASE7_NODES,
)

LOGIC_NODE_PARITY_CATALOG = {
    entry["idname"]: entry
    for entry in _TRACKED_NATIVE_NODES
    if entry.get("idname")
}

LOGIC_NODE_DEFERRED_CATALOG = {
    entry["key"]: entry
    for entry in (
        *_DEFERRED_PHASE4_NODES,
        *_DEFERRED_PHASE5_NODES,
        *_DEFERRED_PHASE7_LOOPS_NODES,
        *_DROPPED_PHASE7_NODES,
    )
}


def catalog_status_for_idname(node_idname):
    if not node_idname.startswith("LogicNative"):
        return LOGIC_NODE_STATUS_IMPLEMENTED
    entry = LOGIC_NODE_PARITY_CATALOG.get(node_idname)
    if entry is None:
        return LOGIC_NODE_STATUS_UNTRACKED
    return entry["status"]


def catalog_native_idnames(*, status=None, visible=None):
    idnames = set()
    for entry in LOGIC_NODE_PARITY_CATALOG.values():
        if status is not None and entry["status"] != status:
            continue
        if visible is not None and entry["visible"] != visible:
            continue
        idnames.add(entry["idname"])
    return frozenset(idnames)


def deferred_native_idnames():
    return frozenset(
        entry["idname"]
        for entry in LOGIC_NODE_DEFERRED_CATALOG.values()
        if entry.get("idname")
    )
